vars: null
stages:
    dev:
        vars: null
        regions:
            us-west-2:
                vars:
                    iamRoleArnLambda: >-
                        arn:aws:iam::908660671515:role/serverless-bot-dev-IamRoleLambda-M75OAZXEI6VN
